## Cadence PVS

- name: Check for Cadence Physical Verification System installation
  stat: path=/shared/software/cadence/PVS161
  changed_when: false
  register: cadence_pvs_folder

- name: Install Cadence PVS
  when: not cadence_pvs_folder.stat.exists
  shell: |
    set -e
    yum install -y libXp
    mkdir -p /tmp/PVS16.13.s346
    tar xf {{ ansible_env.ANSIBLE_INSTALL_SOURCE_DIR }}/PVS16.13.s346.tar.gz -C /tmp/PVS16.13.s346
    mkdir -p /shared/software/cadence/PVS161
    /shared/software/cadence/iscape/bin/iscape.sh -batch majorAction=InstallFromArchive archiveDirectory=/tmp/PVS16.13.s346/PVS16.13.s346/ installDirectory=/shared/software/cadence/PVS161
    rm -rf /tmp/PVS16.13.s346

- name: Install Dependant Packages for ICADV123 and PVS161
  yum:
    name:
      - motif.x86_64
      - motif.i686
      - xorg-x11-fonts-misc
      - libXp.i686
    state: installed
